rvm:
  - 1.8.7
  - 1.9.2
  - ree
  - rbx-2.0

before_script: "sudo -b ntpdate ntp.ubuntu.com pool.ntp.org; exit 0"
script: "bundle exec cucumber"

gemfile:
  - gemfiles/rails2.gemfile
  - gemfiles/rails3.gemfile
  - gemfiles/rails3_1.gemfile
